api_version: go1
application: aecrasher
handlers:

- script: _go_app
  secure: optional
  url: /api/.*

- url: /
  secure: optional
  static_files: index.html
  upload: index.html

runtime: go
version: 1
